github:
  prebuilds:
    pullRequestsFromForks: true

# image: public.ecr.aws/pahudnet/gitpod-workspace:latest

# image:
#   file: .gitpod.Dockerfile

tasks:
  - name: run docker
    command: sudo docker-up & 
  - command: echo "source /usr/share/bash-completion/completions/git" >> $HOME/.bashrc
  - init: ./gradlew --info


# vscode:
#   extensions:
#     - redhat.java
#     - Pivotal.vscode-boot-dev-pack
#     - richardwillis.vscode-gradle
#     - GabrielBB.vscode-lombok
#     - redhat.fabric8-analytics
#     - sonarsource.sonarlint-vscode
