/*
 * This file is generated by jOOQ.
 */
package com.example.demo.cartms.domain.projecttions;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * 購物車資料
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "cart",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_cart_PRIMARY", columnNames = { "cart_number" })
    }
)
public class Cart implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        cartNumber;
    private String        customer;
    private Integer       amount;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public Cart() {}

    public Cart(Cart value) {
        this.cartNumber = value.cartNumber;
        this.customer = value.customer;
        this.amount = value.amount;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public Cart(
        String        cartNumber,
        String        customer,
        Integer       amount,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.cartNumber = cartNumber;
        this.customer = customer;
        this.amount = amount;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>testdb.cart.cart_number</code>. 購物車編號
     */
    @Id
    @Column(name = "cart_number", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCartNumber() {
        return this.cartNumber;
    }

    /**
     * Setter for <code>testdb.cart.cart_number</code>. 購物車編號
     */
    public void setCartNumber(String cartNumber) {
        this.cartNumber = cartNumber;
    }

    /**
     * Getter for <code>testdb.cart.customer</code>. 客戶名稱
     */
    @Column(name = "customer", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCustomer() {
        return this.customer;
    }

    /**
     * Setter for <code>testdb.cart.customer</code>. 客戶名稱
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * Getter for <code>testdb.cart.amount</code>. 金額
     */
    @Column(name = "amount", nullable = false, precision = 10)
    @NotNull
    public Integer getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>testdb.cart.amount</code>. 金額
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>testdb.cart.created_by</code>.
     */
    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>testdb.cart.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>testdb.cart.created_date</code>.
     */
    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>testdb.cart.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>testdb.cart.last_modified_by</code>.
     */
    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>testdb.cart.last_modified_by</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>testdb.cart.last_modified_date</code>.
     */
    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>testdb.cart.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}
